# Generated by Django 2.0.2 on 2018-02-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0003_auto_20180217_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustom',
            old_name='id',
            new_name='id_administrador',
        ),
    ]
