# Generated by Django 2.0.2 on 2018-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0004_auto_20180217_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='ruta_imagen',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
