# Generated by Django 2.0.2 on 2018-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0005_concurso_ruta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='estado',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
