# Generated by Django 2.0.2 on 2018-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0006_auto_20180217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='url_concurso',
            field=models.URLField(null=True),
        ),
    ]
