# Generated by Django 2.0.2 on 2018-02-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0007_auto_20180212_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Empresa',
            field=models.CharField(error_messages={'Emp': 'Error en Emp'}, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Marketing', 'Marketing')], error_messages={'Rol': 'Error en Rol'}, max_length=15),
        ),
    ]
