# Generated by Django 2.0.2 on 2018-02-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0007_auto_20180217_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='ruta_imagen',
        ),
    ]
