# Generated by Django 2.0.2 on 2018-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0008_remove_concurso_ruta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='valor_pagar',
            field=models.IntegerField(max_length=200),
        ),
    ]
