# Generated by Django 2.0.2 on 2018-02-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0009_auto_20180212_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Rol',
        ),
    ]
