# Generated by Django 2.0.2 on 2018-02-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0011_auto_20180212_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='Empresa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='Rol',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
