# Generated by Django 2.0.2 on 2018-02-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0013_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustom',
            old_name='user',
            new_name='user_id',
        ),
    ]
