# Generated by Django 2.0.2 on 2018-02-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0014_auto_20180213_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_id',
        ),
    ]
