# Generated by Django 2.0.2 on 2018-02-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0015_auto_20180214_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
