# Generated by Django 2.0.2 on 2018-02-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0016_auto_20180214_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustom',
            old_name='user_id',
            new_name='user',
        ),
    ]
