# Generated by Django 2.0.2 on 2018-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0017_auto_20180214_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='user',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
