# Generated by Django 2.0.2 on 2018-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0018_auto_20180214_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
