# Generated by Django 2.0.2 on 2018-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0019_auto_20180214_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
