# Generated by Django 2.0.2 on 2018-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0020_auto_20180214_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(auto_created=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
