# Generated by Django 2.0.2 on 2018-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0021_auto_20180214_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(auto_created=True, max_length=150, primary_key=True, serialize=False),
        ),
    ]
