# Generated by Django 2.0.2 on 2018-02-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebConcursos', '0022_auto_20180214_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='user',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
